version: "3"

services:
  web: 
    container_name: tasksapp
    restart: always
    build: .
    ports:
      - "3001:3001"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: tasksmongodb
    image: mongo
    ports:
        - "27018:27017"
    logging:
      driver: none


